name: Update LM Studio

on:
  schedule:
    - cron: '0 0 * * *' # 每天 UTC 时间 0:00 运行 (北京时间 8:00)
  workflow_dispatch: # 允许手动触发

permissions:
  contents: write

jobs:
  update-lmstudio:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Run update script
        run: |
          chmod +x update.sh
          ./update.sh

      - name: Commit and Push changes
        run: |
          # 检查 package.nix 是否有变化
          if [[ -n $(git status --porcelain package.nix) ]]; then
            echo "New version found. Committing..."
            git config --global user.name 'GitHub Actions'
            git config --global user.email 'actions@github.com'
            git add package.nix
            git commit -m "chore: update lmstudio version [skip ci]"
            git push
          else
            echo "No update found."
          fi
